name: Data Engineering Checks
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint isort pytest pytest-cov pandas duckdb

      - name: Check imports with isort
        run: |
          isort --check-only --diff data_engineering/

      - name: Lint with pylint
        run: |
          pylint data_engineering/ --disable=C0111,C0103

      - name: Run tests with pytest
        run: |
          pytest data_engineering/test/ --cov=data_engineering --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
